# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 21:51
from __future__ import unicode_literals

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csvupload',
            name='date',
        ),
        migrations.RemoveField(
            model_name='csvupload',
            name='user',
        ),
        migrations.AddField(
            model_name='csvupload',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='csvupload',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
    ]
