# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 13:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20170921_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csvupload',
            name='shop',
        ),
        migrations.DeleteModel(
            name='CSVUpload',
        ),
    ]
