# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20170923_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='logo',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
