# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20170926_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='shop',
            name='logo',
            field=models.FileField(blank=True, upload_to='shop_logos/'),
        ),
    ]
