# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-04 18:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_search_vector'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomaticProductUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_url', models.URLField(max_length=2000)),
                ('is_compressed', models.BooleanField(default=False)),
                ('compress_format', models.CharField(choices=[('gz', 'GZ'), ('zip', 'ZIP')], max_length=20)),
                ('import_cmd', models.CharField(max_length=2000)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('local_file', models.CharField(blank=True, max_length=2000, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Shop')),
            ],
        ),
    ]
