# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-05 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_automaticproductupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automaticproductupdate',
            name='compress_format',
            field=models.CharField(blank=True, choices=[('gz', 'GZ'), ('zip', 'ZIP')], max_length=20, null=True),
        ),
    ]
