# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-05 17:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20171005_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='automaticproductupdate',
            old_name='import_cmd',
            new_name='last_import_cmd',
        ),
    ]
