# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-05 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20171005_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='automaticproductupdate',
            name='delimiter',
            field=models.CharField(default=';', max_length=2),
        ),
    ]
