# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-05 21:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_automaticproductupdate_delimiter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automaticproductupdate',
            name='last_import_cmd',
        ),
    ]
