# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-01 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20171006_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automaticproductupdate',
            name='delimiter',
            field=models.CharField(default=';', max_length=3),
        ),
    ]
