# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-13 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20171101_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automaticproductupdate',
            name='compress_format',
            field=models.CharField(blank=True, choices=[('zip', 'ZIP')], default='zip', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='automaticproductupdate',
            name='delimiter',
            field=models.CharField(default=',', max_length=3),
        ),
        migrations.AlterField(
            model_name='automaticproductupdate',
            name='is_compressed',
            field=models.BooleanField(default=True),
        ),
    ]
