# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-13 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20180213_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automaticproductupdate',
            name='catalog_url',
            field=models.URLField(max_length=2000, unique=True),
        ),
    ]
