# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-17 13:28
from __future__ import unicode_literals

import django.contrib.postgres.indexes
from django.db import migrations, models
from django.contrib.postgres.operations import BtreeGinExtension


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20180213_1624'),
    ]

    operations = [
        BtreeGinExtension(),
        migrations.AddField(
            model_name='shop',
            name='language',
            field=models.CharField(blank=True, default='spanish', help_text='language to use in full text search', max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='ean',
            field=models.CharField(blank=True, db_index=True, max_length=13),
        ),
        migrations.AlterField(
            model_name='product',
            name='upc',
            field=models.CharField(blank=True, db_index=True, max_length=12),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='search_vector_idx'),
        ),
    ]
