# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-17 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_auto_20180217_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=2000),
        ),
    ]
